# Generated by Django 5.2.7 on 2025-10-28 14:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name for this debt plan', max_length=100)),
                ('method', models.CharField(choices=[('snowball', 'Debt Snowball'), ('avalanche', 'Debt Avalanche'), ('consolidation', 'Debt Consolidation')], help_text='Debt reduction method', max_length=20)),
                ('extra_payment', models.DecimalField(decimal_places=2, default=0, help_text='Extra monthly payment amount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('consolidation_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Consolidated loan interest rate (for consolidation method)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(100)])),
                ('consolidation_term', models.PositiveIntegerField(blank=True, help_text='Consolidated loan term in months', null=True)),
                ('total_debt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_interest_saved', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payoff_months', models.PositiveIntegerField(default=0, help_text='Estimated months to pay off all debt')),
                ('total_payments', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused')], default='draft', max_length=20)),
                ('is_active', models.BooleanField(default=False, help_text="Whether this is the user's active plan")),
                ('plan_data', models.JSONField(default=dict, help_text='Detailed plan calculation data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Debt Plan',
                'verbose_name_plural': 'Debt Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.PositiveIntegerField(help_text='Month number in the plan')),
                ('actual_payment', models.DecimalField(decimal_places=2, help_text='Actual payment made this month', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True, help_text="Notes about this month's progress")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='plans.debtplan')),
            ],
            options={
                'verbose_name': 'Plan Progress',
                'verbose_name_plural': 'Plan Progress',
                'ordering': ['-month'],
                'unique_together': {('plan', 'month')},
            },
        ),
    ]
