# Generated by Django 5.2.7 on 2025-10-28 14:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name or description of the loan', max_length=100)),
                ('loan_type', models.CharField(choices=[('credit_card', 'Credit Card'), ('personal_loan', 'Personal Loan'), ('student_loan', 'Student Loan'), ('auto_loan', 'Auto Loan'), ('mortgage', 'Mortgage'), ('medical_debt', 'Medical Debt'), ('other', 'Other')], default='other', max_length=20)),
                ('creditor', models.CharField(blank=True, help_text='Name of the creditor/lender', max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, help_text='Current outstanding balance', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Annual interest rate (APR) in percent', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('minimum_payment', models.DecimalField(decimal_places=2, help_text='Minimum monthly payment required', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('original_balance', models.DecimalField(blank=True, decimal_places=2, help_text='Original loan amount (if different from current balance)', max_digits=12, null=True)),
                ('term_months', models.PositiveIntegerField(blank=True, help_text='Original term in months (if applicable)', null=True)),
                ('due_date', models.DateField(blank=True, help_text='Monthly due date', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this loan is still active')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the loan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
                'ordering': ['-created_at'],
            },
        ),
    ]
