# Generated by Django 5.2.7 on 2025-10-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='remaining_term_months',
            field=models.PositiveIntegerField(blank=True, help_text='Remaining term in months', null=True),
        ),
    ]
